"use client";

import { startTransition, useEffect, useState } from "react";

type Stage = "create" | "discovery" | "positioning" | "personality" | "battle" | "critic" | "selection" | "visual" | "voice" | "guardian" | "launch" | "kit" | "workflow";
type Direction = { direction_name: string; strategic_territory: string; concept: string; emotional_territory: string; naming_style: string; sample_names: string[]; tagline_direction: string; personality: string[]; strengths: string[]; weaknesses: string[] };
type Visual = { color_palette: string[]; typography: string[]; imagery_style: string; composition: string; symbols: string[]; ui_direction: string; things_to_avoid: string[] };
type Voice = { tone: string; vocabulary: string[]; sentence_style: string; writing_rules: string[]; words_to_use: string[]; words_to_avoid: string[]; example_headline: string; example_product_description: string; example_social_post: string; example_cta: string };
type Guardian = { overall_evaluation: string; audience_fit: number; positioning_alignment: number; personality_alignment: number; voice_alignment: number; genericity_risk: number; problems: string[]; explanation: string; recommendations: string[]; improved_version: string };
type Launch = { headline: string; subheadline: string; one_line_pitch: string; product_description: string; social_post: string; cta: string };
type State = { id?: string; name: string; idea: string; audience?: string; problem?: string; alternatives?: string; positioning?: { category: string; target_audience: string; core_problem: string; value_proposition: string; differentiator: string; positioning_statement: string; competitive_angle: string }; personality?: { traits: string[]; principles: string[]; traits_to_avoid: string[] }; directions?: Direction[]; evaluations?: Array<{ scores: Record<string, number>; decision: string; issues: string[]; evidence: string[]; recommendations: string[] }>; selected?: number; visual?: Visual; voice?: Voice; guardian?: Guardian; launch?: Launch; final?: { name: string; tagline: string; pitch: string } };

const demo: State = { id: "demo", name: "Campus Relay", idea: "A platform that helps college students find teammates for hackathons.", audience: "College students who want to build, but do not yet have a crew.", problem: "Students waste the first hours of a hackathon searching for reliable teammates.", alternatives: "Group chats, Discord servers, and asking around at the event.", positioning: { category: "guided coordination platform", target_audience: "College students who want to build", core_problem: "Students waste the first hours searching for reliable teammates.", value_proposition: "Find the right teammates before the clock starts, then ship with momentum.", differentiator: "It turns a vague need into a relevant, human-feeling match.", positioning_statement: "For college builders who need a crew, Campus Relay makes the right teammate easy to find before the clock starts.", competitive_angle: "Clarity and fit over noisy directories." }, personality: { traits: ["Open", "Resourceful", "Specific", "Momentum-driven"], principles: ["Make the next step obvious", "Invite before you impress", "Reward useful momentum"], traits_to_avoid: ["Corporate", "Generic", "Overly formal"] }, selected: 1 };

const steps: Array<[Stage, string]> = [["create", "Idea"], ["discovery", "Discovery"], ["positioning", "Positioning"], ["personality", "Personality"], ["battle", "Brand Battle"], ["critic", "Critic"], ["selection", "Selection"], ["visual", "Visual Identity"], ["voice", "Brand Voice"], ["guardian", "Guardian"], ["launch", "Launch"], ["kit", "Brand Kit"], ["workflow", "Workflow"]];

function localDirections(state: State): Direction[] { const subject = state.name; return [{ direction_name: "Make it real", strategic_territory: "Builder / technical", concept: `A practical engine for making ${subject} useful fast.`, emotional_territory: "Capability and momentum", naming_style: "Compact verbs and construction language", sample_names: ["Forge", "Stackmate", "Buildloop"], tagline_direction: "Find the right move. Make it real.", personality: ["Precise", "Energetic", "Capable"], strengths: ["Feels actionable", "Signals progress"], weaknesses: ["Can sound like a tool"] }, { direction_name: "Find your people", strategic_territory: "Community / crew", concept: "A welcoming signal for the people who make a good idea click.", emotional_territory: "Belonging and recognition", naming_style: "Warm, human, easy-to-say names", sample_names: ["Kinship", "Orbit", "Roommate"], tagline_direction: "Good ideas need the right room.", personality: ["Open", "Warm", "Encouraging"], strengths: ["Lowers first-step anxiety", "Strong emotional hook"], weaknesses: ["Needs proof of speed"] }, { direction_name: "Enter the arena", strategic_territory: "Competitive / arena", concept: "A rallying point for ambitious people working against the clock.", emotional_territory: "Urgency and earned pride", naming_style: "Short, kinetic, game-adjacent names", sample_names: ["Rally", "Bracket", "Draftday"], tagline_direction: "Build your winning team.", personality: ["Bold", "Fast", "Ambitious"], strengths: ["Memorable energy", "Creates urgency"], weaknesses: ["May intimidate beginners"] }]; }

function localVisual(state: State): Visual { return { color_palette: ["Deep ink #1D2924", "Signal orange #F36B3B", "Soft mint #CBE8D8", "Warm paper #F7F8F3"], typography: ["Expressive grotesk headlines", "Compact mono labels", "Readable humanist body"], imagery_style: `Real ${state.audience || "people"} making progress together, captured in candid motion.`, composition: "Open editorial compositions with a clear focal point and generous breathing room.", symbols: ["Relay marks", "Connected paths", "Directional arrows"], ui_direction: "Warm signal colors, crisp borders, and generous space around decisions.", things_to_avoid: ["Stock corporate scenes", "Generic gradients", "Overly competitive cues"] }; }
function localVoice(state: State): Voice { return { tone: "Direct, warm, useful, and quietly confident.", vocabulary: ["crew", "make", "ship", "right fit", "next move"], sentence_style: "Short active sentences with a human invitation.", writing_rules: ["Lead with the useful outcome", "Use active verbs", "Invite before you impress", "Name the friction plainly"], words_to_use: ["find", "build", "together", "ready", "move"], words_to_avoid: ["seamless", "comprehensive", "leverage", "solution"], example_headline: state.directions?.[state.selected ?? 1]?.tagline_direction || "Good ideas need the right room.", example_product_description: state.positioning?.value_proposition || "Make the next move with the right people.", example_social_post: "Your next build gets better when the right people are in the room.", example_cta: "Find your people" }; }
function localGuardian(state: State, content: string): Guardian { const generic = /comprehensive|seamless|leverage|solution/i.test(content); return { overall_evaluation: generic ? "Revise: the message loses the selected brand's human, specific signal." : "Keep: the message is aligned with the established brand system.", audience_fit: generic ? 6 : 9, positioning_alignment: generic ? 7 : 9, personality_alignment: generic ? 5 : 9, voice_alignment: generic ? 4 : 9, genericity_risk: generic ? 8 : 2, problems: generic ? ["Generic corporate vocabulary", "Weak audience signal"] : [], explanation: "The selected voice asks for active, human language tied to a concrete next move.", recommendations: generic ? ["Use active verbs and name a concrete outcome.", "Replace abstract claims with a specific user benefit."] : ["Keep the concrete audience and outcome visible."], improved_version: generic ? `${state.name}: ${state.voice?.example_cta || "Find your people"}. ${state.positioning?.value_proposition || "Make the next move together."}` : content }; }
function localLaunch(state: State): Launch { const direction = state.directions?.[state.selected ?? 1]; const name = state.final?.name || direction?.sample_names[0] || state.name; const tagline = direction?.tagline_direction || "Make the next move together."; return { headline: tagline, subheadline: state.positioning?.value_proposition || "Make a better first move.", one_line_pitch: `${name} helps ${state.positioning?.target_audience?.toLowerCase() || "people"} make the right next move.`, product_description: state.positioning?.positioning_statement || "A clearer way to move forward with the right people.", social_post: `Meet ${name}: ${tagline} Find your next move with people who get it.`, cta: state.voice?.example_cta || "Find your people" }; }

export default function Home() {
  const [stage, setStage] = useState<Stage>("create");
  const [state, setState] = useState<State>(demo);
  const [name, setName] = useState(""); const [idea, setIdea] = useState(""); const [answers, setAnswers] = useState({ audience: "", problem: "", alternatives: "" });
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [demoMode, setDemoMode] = useState(false); const [hydrated, setHydrated] = useState(false);
  const BACKEND_URL = (process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:8000").replace(/\/$/, "");
  async function api<T>(path: string, options?: RequestInit): Promise<T> { const response = await fetch(`${BACKEND_URL}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(options?.headers || {}) } }); if (!response.ok) { const detail = await response.text().catch(() => ""); throw new Error(`Backend ${response.status} on ${path}${detail ? `: ${detail.slice(0, 300)}` : ""}. BrandState preserved; retry.`); } return response.json() as Promise<T>; }
  const selected = state.directions?.[state.selected ?? 1];
  const backendLive = !demoMode && !!state.id && state.id !== "demo";
  useEffect(() => {
    try {
      const snapshot = JSON.parse(window.localStorage.getItem("brandforge-mvp-v2") || "null");
      startTransition(() => {
        if (snapshot?.stage) setStage(snapshot.stage);
        if (snapshot?.state) setState(snapshot.state);
        if (snapshot?.name) setName(snapshot.name);
        if (snapshot?.idea) setIdea(snapshot.idea);
        if (snapshot?.answers) setAnswers(snapshot.answers);
        if (typeof snapshot?.demoMode === "boolean") setDemoMode(snapshot.demoMode);
        setHydrated(true);
      });
    } catch {
      window.localStorage.removeItem("brandforge-mvp-v2"); window.localStorage.removeItem("brandforge-mvp");
      startTransition(() => setHydrated(true));
    }
  }, []);
  useEffect(() => {
    if (hydrated) window.localStorage.setItem("brandforge-mvp-v2", JSON.stringify({ stage, state, name, idea, answers, demoMode }));
  }, [answers, demoMode, hydrated, idea, name, stage, state]);
  const run = async (next: Stage, action: () => Promise<void>) => { setBusy(true); setError(""); try { await action(); setStage(next); } catch (e) { setError(e instanceof Error ? e.message : "Something went wrong. Your current state is preserved."); } finally { setBusy(false); } };
  const refreshFromBackend = async (projectId: string) => { const full = await api<{ positioning?: State["positioning"]; personality?: State["personality"]; brand_directions?: Direction[]; evaluation?: { evaluations?: State["evaluations"] }; selected_direction?: Direction | null; visual_identity?: Visual; brand_voice?: Voice; guardian?: Guardian; launch?: Launch; final_brand?: State["final"] | null; discovery?: { problem?: string; target_users?: string[]; existing_alternatives?: string[] } }>(`/api/projects/${projectId}`); setState(prev => ({ ...prev, positioning: full.positioning ?? prev.positioning, personality: full.personality ?? prev.personality, directions: (full.brand_directions && full.brand_directions.length ? full.brand_directions : prev.directions), evaluations: (full.evaluation?.evaluations && full.evaluation.evaluations.length ? full.evaluation.evaluations : prev.evaluations), visual: (full.visual_identity && Object.keys(full.visual_identity).length ? full.visual_identity : prev.visual), voice: (full.brand_voice && Object.keys(full.brand_voice).length ? full.brand_voice : prev.voice), guardian: (full.guardian && full.guardian.overall_evaluation ? full.guardian : prev.guardian), launch: (full.launch && full.launch.headline ? full.launch : prev.launch), final: full.final_brand ?? prev.final, audience: full.discovery?.target_users?.[0] ?? prev.audience, problem: full.discovery?.problem ?? prev.problem, alternatives: full.discovery?.existing_alternatives?.[0] ?? prev.alternatives, selected: full.selected_direction && full.brand_directions ? Math.max(0, full.brand_directions.findIndex(d => d.direction_name === full.selected_direction?.direction_name)) : prev.selected })); };
  const create = () => run("discovery", async () => { if (!name.trim() || idea.trim().length < 10) throw new Error("Add a project name and an idea of at least 10 characters."); if (demoMode) { setState({ id: "demo", name: name.trim(), idea: idea.trim() }); return; } const created = await api<{ id: string }>(`/api/projects`, { method: "POST", body: JSON.stringify({ name: name.trim(), idea: idea.trim() }) }); setState({ id: created.id, name: name.trim(), idea: idea.trim() }); });
  const discover = () => run("positioning", async () => { if (demoMode) { const audience = (answers.audience || "early adopters").trim().replace(/[.!?]+$/, ""); const problem = (answers.problem || state.idea).trim().replace(/[.!?]+$/, ""); const next = { ...state, audience, problem, alternatives: answers.alternatives }; setState(next); return; } if (!state.id) throw new Error("Create the project first. BrandState preserved; retry."); await api(`/api/projects/${state.id}/discovery`, { method: "POST", body: JSON.stringify({ answers: { target_users: answers.audience, problem: answers.problem, alternatives: answers.alternatives } }) }); await refreshFromBackend(state.id); });
  const strategy = () => run("personality", async () => { if (demoMode) { const next = { ...state }; setState(next); return; } if (!state.id) throw new Error("Create the project first. BrandState preserved; retry."); await api(`/api/projects/${state.id}/positioning`, { method: "POST", body: "{}" }); await refreshFromBackend(state.id); });
  const personalityNext = () => run("battle", async () => { if (demoMode) { setState({ ...state, directions: localDirections(state) }); return; } if (!state.id) throw new Error("Create the project first. BrandState preserved; retry."); await api(`/api/projects/${state.id}/personality`, { method: "POST", body: "{}" }); await refreshFromBackend(state.id); });
  const battle = () => run("critic", async () => { if (demoMode) { setState({ ...state, directions: localDirections(state) }); return; } if (!state.id) throw new Error("Create the project first. BrandState preserved; retry."); await api(`/api/projects/${state.id}/battle`, { method: "POST", body: "{}" }); await refreshFromBackend(state.id); });
  const criticNext = () => run("selection", async () => { if (demoMode) { const evaluations = (state.directions || []).map((_, i) => ({ decision: i === 1 ? "KEEP" : "REVISE", scores: { audience_fit: i === 1 ? 9 : 7, problem_alignment: 8, distinctiveness: i === 1 ? 8 : 6, memorability: i === 2 ? 8 : 7, clarity: 8, personality_alignment: 8, genericity_risk: i === 1 ? 2 : 6, consistency: 8 }, issues: i === 1 ? [] : ["The territory needs a more ownable verbal hook."], evidence: ["This score uses the submitted audience, problem, and positioning."], recommendations: i === 1 ? ["Protect the welcoming language in future copy."] : ["Replace familiar category language with a sharper cue."] })); setState({ ...state, evaluations }); return; } if (!state.id) throw new Error("Create the project first. BrandState preserved; retry."); await api(`/api/projects/${state.id}/critic`, { method: "POST", body: "{}" }); await refreshFromBackend(state.id); });
  const select = (index: number) => run("visual", async () => { const direction = state.directions?.[index]; if (!direction) throw new Error("Choose a valid direction."); if (demoMode) { setState({ ...state, selected: index, visual: localVisual({ ...state, selected: index }), final: { name: direction.sample_names[0], tagline: direction.tagline_direction, pitch: state.positioning?.value_proposition || "A clearer way to make the next move." } }); return; } if (!state.id) throw new Error("Create the project first. BrandState preserved; retry."); await api(`/api/projects/${state.id}/select-direction`, { method: "POST", body: JSON.stringify({ direction_index: index }) }); await refreshFromBackend(state.id); });
  const prepareVoice = () => run("voice", async () => { if (demoMode) { setState({ ...state, voice: localVoice(state) }); return; } if (!state.id) throw new Error("Create the project first. BrandState preserved; retry."); await api(`/api/projects/${state.id}/visual`, { method: "POST", body: "{}" }); await refreshFromBackend(state.id); });
  const openGuardian = () => run("guardian", async () => { if (demoMode) { setState({ ...state, voice: state.voice || localVoice(state) }); return; } if (!state.id) throw new Error("Create the project first. BrandState preserved; retry."); await api(`/api/projects/${state.id}/voice`, { method: "POST", body: "{}" }); await refreshFromBackend(state.id); });
  const guardian = (content: string) => run("launch", async () => { if (demoMode) { setState({ ...state, guardian: localGuardian(state, content) }); return; } if (!state.id) throw new Error("Create the project first. BrandState preserved; retry."); await api(`/api/projects/${state.id}/guardian`, { method: "POST", body: JSON.stringify({ content }) }); await refreshFromBackend(state.id); });
  const launch = () => run("kit", async () => { if (demoMode) { setState({ ...state, launch: localLaunch(state) }); return; } if (!state.id) throw new Error("Create the project first. BrandState preserved; retry."); await api(`/api/projects/${state.id}/launch`, { method: "POST", body: "{}" }); await api(`/api/projects/${state.id}/brand-kit`); await refreshFromBackend(state.id); });
  const loadDemo = () => { setDemoMode(true); setState({ ...demo, directions: localDirections(demo) }); setAnswers({ audience: demo.audience || "", problem: demo.problem || "", alternatives: demo.alternatives || "" }); setStage("discovery"); };
  return <main className="mvp-shell"><aside className="mvp-sidebar"><div className="brand-mark"><span>BF</span><div><strong>BRANDFORGE</strong><small>AI BRAND STUDIO</small></div></div><div className="demo-pill"><i /> {demoMode ? "DEMO MODE" : "LIVE MODE"}</div><button className="mode-toggle" onClick={() => setDemoMode(!demoMode)}>{demoMode ? "Switch to live mode" : "Use demo mode"}</button><nav>{steps.map(([key, label], i) => <button key={key} onClick={() => key === "kit" && state.final ? setStage(key) : key === "workflow" ? setStage(key) : undefined} className={stage === key ? "active" : ""}><span>{String(i + 1).padStart(2, "0")}</span>{label}{stage === key && <b>›</b>}</button>)}</nav><button className="reset-link" onClick={() => { setStage("create"); setState(demo); }}>+ New brand</button></aside><section className="mvp-content"><header className="mvp-topbar"><span>WORKSPACE / {state.name.toUpperCase()}</span><span className="live-chip">● {demoMode ? "DEMO DATA" : "LIVE BACKEND"}</span></header>{error && <div className="error-banner">{error}</div>}{busy && <div className="processing">Processing structured brand state...</div>}{stage === "create" && <Create name={name} setName={setName} idea={idea} setIdea={setIdea} onCreate={create} onDemo={loadDemo} />}{stage === "discovery" && <Discovery answers={answers} setAnswers={setAnswers} onNext={discover} />}{stage === "positioning" && <Positioning state={state} onNext={strategy} />}{stage === "personality" && <PersonalityStage state={state} onNext={personalityNext} />}{stage === "battle" && <Battle state={state} onNext={battle} />}{stage === "critic" && <Critic state={state} onNext={criticNext} onSelect={select} />}{stage === "selection" && <Critic state={state} onNext={() => setStage("visual")} onSelect={select} />}{stage === "visual" && <VisualStage state={state} onNext={prepareVoice} live={backendLive} />}{stage === "voice" && <VoiceStage state={state} onNext={openGuardian} live={backendLive} />}{stage === "guardian" && <GuardianStage state={state} onCheck={guardian} />}{stage === "launch" && <LaunchStage state={state} onNext={launch} live={backendLive} />}{stage === "kit" && <Kit state={state} selected={selected} live={backendLive} />}{stage === "workflow" && <Workflow state={state} onNavigate={setStage} />}</section></main>;
}

function Create({ name, setName, idea, setIdea, onCreate, onDemo }: { name: string; setName: (x: string) => void; idea: string; setIdea: (x: string) => void; onCreate: () => void; onDemo: () => void }) { return <div className="mvp-center"><p className="eyebrow">START WITH A SIGNAL</p><h1>Turn a rough idea into<br /><em>a brand people remember.</em></h1><p className="lede">BrandForge moves in stages: understand, position, challenge, choose. You stay in the loop at every decision.</p><div className="create-form"><label>PROJECT NAME<input value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Campus Relay" /></label><label>ROUGH IDEA<textarea value={idea} onChange={e => setIdea(e.target.value)} placeholder="What are you building, for whom, and why does it matter?" /></label><button className="primary-button" onClick={onCreate}>Start discovery <span>→</span></button></div><button className="demo-link" onClick={onDemo}>Open Campus Relay demo ↗</button></div>; }
function Discovery({ answers, setAnswers, onNext }: { answers: { audience: string; problem: string; alternatives: string }; setAnswers: (x: { audience: string; problem: string; alternatives: string }) => void; onNext: () => void }) { return <div className="mvp-page"><p className="eyebrow">STAGE 01 / ADAPTIVE DISCOVERY</p><h1>Let&apos;s find the real<br /><em>problem underneath.</em></h1><p className="lede">These questions are chosen because their answers change the brand strategy. Nothing decorative gets in the way.</p><div className="question-grid">{[["audience", "Who is the primary user you want to win first?", "Audience language determines the brand center of gravity."], ["problem", "What frustrating problem are they experiencing today?", "A specific tension produces a sharper position."], ["alternatives", "What do they use or do instead right now?", "The alternative reveals where your difference can matter."]].map(([key, q, why]) => <label key={key}><span>QUESTION {key === "audience" ? "01" : key === "problem" ? "02" : "03"}</span><strong>{q}</strong><small>{why}</small><textarea value={answers[key as keyof typeof answers]} onChange={e => setAnswers({ ...answers, [key]: e.target.value })} /></label>)}</div><button className="primary-button" onClick={onNext}>Build my positioning <span>→</span></button></div>; }
function Positioning({ state, onNext }: { state: State; onNext: () => void }) { const p = state.positioning; return <div className="mvp-page"><p className="eyebrow">STAGE 02 / POSITIONING</p><h1>Here&apos;s the signal<br /><em>we found.</em></h1><div className="strategy-card"><div><small>CATEGORY</small><strong>{p?.category}</strong></div><div><small>CORE PROBLEM</small><p>{p?.core_problem}</p></div><div><small>VALUE PROPOSITION</small><p>{p?.value_proposition}</p></div><div><small>DIFFERENTIATOR</small><p>{p?.differentiator}</p></div><div className="full"><small>POSITIONING STATEMENT</small><strong>{p?.positioning_statement}</strong></div></div><button className="primary-button" onClick={onNext}>Shape the personality <span>→</span></button></div>; }
function PersonalityStage({ state, onNext }: { state: State; onNext: () => void }) { return <div className="mvp-page"><p className="eyebrow">STAGE 03 / PERSONALITY</p><h1>Give the strategy<br /><em>a point of view.</em></h1><p className="lede">These traits are derived from the audience and positioning, so the brand can behave consistently under pressure.</p><div className="strategy-card personality-card"><div className="full"><small>TRAITS</small><div className="tags">{state.personality?.traits.map(trait => <span key={trait}>{trait}</span>)}</div></div><div><small>PRINCIPLES</small>{state.personality?.principles.map(principle => <p key={principle}>+ {principle}</p>)}</div><div><small>AVOID</small>{state.personality?.traits_to_avoid.map(trait => <p key={trait} className="risk">{trait}</p>)}</div></div><button className="primary-button" onClick={onNext}>Enter the Brand Battle <span>→</span></button></div>; }
function Battle({ state, onNext }: { state: State; onNext: () => void }) { return <div className="mvp-page wide"><p className="eyebrow">STAGE 04 / BRAND BATTLE</p><h1>Three ways to<br /><em>own the idea.</em></h1><p className="lede">These directions are strategic territories, not random name lists. Compare the emotional bet each one makes.</p><div className="battle-grid">{state.directions?.map((d, i) => <article className={`mvp-direction d${i}`} key={d.direction_name}><small>0{i + 1} / {d.strategic_territory.toUpperCase()}</small><h2>{d.direction_name}</h2><p>{d.concept}</p><div className="names">{d.sample_names.map(n => <span key={n}>{n}</span>)}</div><hr /><small>EMOTIONAL TERRITORY</small><strong>{d.emotional_territory}</strong><small>NAMING STYLE</small><strong>{d.naming_style}</strong><small>STRENGTHS</small><p>{d.strengths.join(" · ")}</p><small>WEAKNESS</small><p className="risk">{d.weaknesses.join(" · ")}</p></article>)}</div><button className="primary-button" onClick={onNext}>Challenge the directions <span>→</span></button></div>; }
function Critic({ state, onNext, onSelect }: { state: State; onNext: () => void; onSelect: (i: number) => void }) { return <div className="mvp-page wide"><p className="eyebrow">STAGE 05 / ANTI-GENERIC CRITIC</p><h1>Keep the strong.<br /><em>Challenge the easy.</em></h1><p className="lede">The critic checks every direction against your audience, problem, and personality. Scores are signals, not scientific measurements.</p><div style={{ marginBottom: 16 }}><button className="primary-button" onClick={onNext}>Run critic on these directions <span>→</span></button></div><div className="critic-list">{state.directions?.map((d, i) => { const e = state.evaluations?.[i]; return <article key={d.direction_name}><div><small>{d.strategic_territory.toUpperCase()}</small><h2>{d.direction_name}</h2><p>{e?.evidence.join(" ")}</p></div><div className="score-box"><strong>{e?.scores.audience_fit}/10</strong><small>AUDIENCE FIT</small><strong>{e?.scores.distinctiveness}/10</strong><small>DISTINCTIVE</small></div><div className="critic-note"><b>{e?.decision}</b><p>{e?.issues.length ? e.issues.join(" ") : "Strongest fit: clear, welcoming, and connected to the stated problem."}</p><button onClick={() => onSelect(i)}>Select direction →</button></div></article> })}</div></div>; }
function VisualStage({ state, onNext, live }: { state: State; onNext: () => void; live?: boolean }) { const visual = state.visual || (live ? undefined : localVisual(state)); if (!visual) return <div className="mvp-page"><p className="eyebrow">STAGE 06 / VISUAL IDENTITY</p><h1>Make the strategy<br /><em>visible.</em></h1><p className="lede">Select a direction first, then generate the visual system from the live backend.</p></div>; return <div className="mvp-page wide"><p className="eyebrow">STAGE 06 / VISUAL IDENTITY</p><h1>Make the strategy<br /><em>visible.</em></h1><p className="lede">This visual system follows the selected {state.directions?.[state.selected ?? 1]?.strategic_territory} direction and the audience signal from Discovery.</p><div className="system-grid"><section className="system-card color-card"><small>COLOR PALETTE</small><div className="swatches large"><i /><i /><i /><i /></div><p>{visual.color_palette.join(" · ")}</p></section><section className="system-card"><small>TYPOGRAPHY</small>{visual.typography.map(item => <strong key={item}>{item}</strong>)}<small>COMPOSITION</small><p>{visual.composition}</p></section><section className="system-card"><small>IMAGERY + UI</small><p>{visual.imagery_style}</p><p>{visual.ui_direction}</p><small>SYMBOLS</small><p>{visual.symbols.join(" · ")}</p></section><section className="system-card avoid"><small>THINGS TO AVOID</small><p>{visual.things_to_avoid.join(" · ")}</p></section></div><button className="primary-button" onClick={onNext}>Shape the brand voice <span>→</span></button></div>; }
function VoiceStage({ state, onNext, live }: { state: State; onNext: () => void; live?: boolean }) { const voice = state.voice || (live ? undefined : localVoice(state)); if (!voice) return <div className="mvp-page"><p className="eyebrow">STAGE 07 / BRAND VOICE</p><h1>Sound like<br /><em>yourself.</em></h1><p className="lede">Generate the visual system first, then generate voice from the live backend.</p></div>; return <div className="mvp-page wide"><p className="eyebrow">STAGE 07 / BRAND VOICE</p><h1>Sound like<br /><em>yourself.</em></h1><div className="voice-layout"><section className="voice-hero"><small>TONE</small><h2>{voice.tone}</h2><small>EXAMPLE HEADLINE</small><strong>{voice.example_headline}</strong><small>CTA</small><button className="text-button">{voice.example_cta} ↗</button></section><section className="system-card"><small>WRITING RULES</small>{voice.writing_rules.map(rule => <p className="rule" key={rule}>+ {rule}</p>)}<small>USE</small><div className="tags">{voice.words_to_use.map(word => <span key={word}>{word}</span>)}</div><small>AVOID</small><div className="tags avoid-tags">{voice.words_to_avoid.map(word => <span key={word}>{word}</span>)}</div></section></div><button className="primary-button" onClick={onNext}>Open Brand Guardian <span>→</span></button></div>; }
function GuardianStage({ state, onCheck }: { state: State; onCheck: (content: string) => void }) { const [content, setContent] = useState("We are launching our new feature next week. It is a comprehensive solution for all your collaboration needs."); return <div className="mvp-page wide"><p className="eyebrow">STAGE 08 / BRAND GUARDIAN</p><h1>Keep the signal<br /><em>intact.</em></h1><p className="lede">Paste future content. Guardian compares it against the selected direction, positioning, personality, and voice.</p><div className="guardian-layout"><section className="guardian-editor"><small>CONTENT TO CHECK</small><textarea value={content} onChange={event => setContent(event.target.value)} /><button className="primary-button" onClick={() => onCheck(content)}>Run guardian check <span>→</span></button></section>{state.guardian ? <section className="guardian-result"><small>EVALUATION</small><h2>{state.guardian.overall_evaluation}</h2><div className="guardian-scores"><b>{state.guardian.audience_fit}<small>Audience</small></b><b>{state.guardian.voice_alignment}<small>Voice</small></b><b>{state.guardian.genericity_risk}<small>Generic risk</small></b></div><p>{state.guardian.explanation}</p><small>IMPROVED VERSION</small><strong>{state.guardian.improved_version}</strong></section> : <section className="guardian-result empty"><span>◎</span><p>Your evidence, scores, and improved version will appear here.</p></section>}</div></div>; }
function LaunchStage({ state, onNext, live }: { state: State; onNext: () => void; live?: boolean }) { const launch = state.launch || (live ? undefined : localLaunch(state)); if (!launch) return <div className="mvp-page"><p className="eyebrow">STAGE 09 / LAUNCH CONTENT</p><h1>Ready to<br /><em>ship the signal.</em></h1><p className="lede">Run Guardian first, then generate launch content from the live backend.</p></div>; return <div className="mvp-page wide"><p className="eyebrow">STAGE 09 / LAUNCH CONTENT</p><h1>Ready to<br /><em>ship the signal.</em></h1><div className="launch-grid"><section className="launch-feature"><small>LANDING PAGE HEADLINE</small><h2>{launch.headline}</h2><p>{launch.subheadline}</p><button className="primary-button" onClick={onNext}>Open final Brand Kit <span>→</span></button></section><section className="system-card"><small>ONE-LINE PITCH</small><strong>{launch.one_line_pitch}</strong><small>PRODUCT DESCRIPTION</small><p>{launch.product_description}</p><small>SOCIAL POST</small><p>{launch.social_post}</p><small>CTA</small><strong>{launch.cta}</strong></section></div></div>; }
function Workflow({ state, onNavigate }: { state: State; onNavigate: (stage: Stage) => void }) { const rows: Array<[Stage, string, string, string]> = [["discovery", "Understand the audience and problem", state.idea, "Questions + discovery context"], ["positioning", "Turn insight into a strategic angle", "Discovery answers", "Positioning statement"], ["personality", "Define how the brand should behave", "Positioning", "Traits + principles"], ["battle", "Generate distinct territories", "Positioning + personality", "Three directions"], ["critic", "Challenge generic choices", "Three directions", "Scores + recommendations"], ["visual", "Translate strategy into a visual system", "Selected direction", "Palette + composition"], ["voice", "Make messages sound consistent", "Personality + positioning", "Voice rules + examples"], ["guardian", "Check future content", "Final brand state", "Alignment report"], ["launch", "Create launch-ready copy", "Voice + positioning", "Launch content"], ["kit", "Deliver the coherent system", "All prior stages", "Final Brand Kit"], ["kit", "Export the complete brand system", "All prior stages", "Brand Kit delivery"]]; return <div className="mvp-page wide"><p className="eyebrow">WORKFLOW / DECISION TRACE</p><h1>Every stage leaves<br /><em>a trace.</em></h1><div className="workflow-table">{rows.map(([key, purpose, input, output], index) => <button key={`${key}-${index}`} onClick={() => onNavigate(key)}><span>{String(index + 1).padStart(2, "0")}</span><strong>{purpose}</strong><small>INPUT / {input}</small><small>OUTPUT / {output}</small></button>)}</div></div>; }
function Kit({ state, selected, live }: { state: State; selected?: Direction; live?: boolean }) { const visual = state.visual || (live ? undefined : localVisual(state)); const voice = state.voice || (live ? undefined : localVoice(state)); const launch = state.launch || (live ? undefined : localLaunch(state)); if (!visual || !voice || !launch) return <div className="mvp-page"><p className="eyebrow">STAGE 10 / FINAL BRAND KIT</p><h1>Incomplete<br /><em>system.</em></h1><p className="lede">Generate visual, voice, guardian, and launch from the live backend before opening the kit.</p></div>; return <div className="mvp-page wide"><p className="eyebrow">STAGE 10 / FINAL BRAND KIT</p><h1>{state.final?.name || selected?.sample_names[0]}</h1><p className="lede">A coherent system built from your discovery, strategy, selected direction, visual identity, voice, and launch content.</p><div className="kit-hero"><small>TAGLINE</small><h2>{state.final?.tagline || selected?.tagline_direction}</h2><p>{state.final?.pitch}</p></div><div className="kit-columns"><section><small>STRATEGY</small><h3>{state.positioning?.value_proposition}</h3><p>{state.positioning?.positioning_statement}</p></section><section><small>PERSONALITY</small><div className="tags">{state.personality?.traits.map(t => <span key={t}>{t}</span>)}</div><p>Principles: {state.personality?.principles.join(" · ")}</p></section><section><small>VISUAL IDENTITY</small><div className="swatches"><i /><i /><i /><i /></div><p>{visual.ui_direction}</p></section><section><small>VOICE</small><h3>{voice.tone}</h3><p>{voice.writing_rules.join(" · ")}</p></section><section><small>LAUNCH</small><h3>{launch.headline}</h3><p>{launch.subheadline}</p><button className="text-button" onClick={() => navigator.clipboard?.writeText(launch.headline)}>Copy headline ↗</button></section><section><small>QUALITY CHECK</small><h3>Audience fit 9 / 10</h3><p>Distinctive 8 / 10 · Clarity 8 / 10 · Consistency 8 / 10 · Genericity risk 2 / 10</p></section></div></div>; }
