"use client";

import { startTransition, useEffect, useState } from "react";

type Stage = "create" | "discovery" | "positioning" | "battle" | "critic" | "kit";
type Direction = { direction_name: string; strategic_territory: string; concept: string; emotional_territory: string; naming_style: string; sample_names: string[]; tagline_direction: string; personality: string[]; strengths: string[]; weaknesses: string[] };
type State = { id?: string; name: string; idea: string; audience?: string; problem?: string; alternatives?: string; positioning?: { category: string; target_audience: string; core_problem: string; value_proposition: string; differentiator: string; positioning_statement: string; competitive_angle: string }; personality?: { traits: string[]; principles: string[]; traits_to_avoid: string[] }; directions?: Direction[]; evaluations?: Array<{ scores: Record<string, number>; decision: string; issues: string[]; evidence: string[]; recommendations: string[] }>; selected?: number; final?: { name: string; tagline: string; pitch: string } };

const demo: State = { id: "demo", name: "Campus Relay", idea: "A platform that helps college students find teammates for hackathons.", audience: "College students who want to build, but do not yet have a crew.", problem: "Students waste the first hours of a hackathon searching for reliable teammates.", alternatives: "Group chats, Discord servers, and asking around at the event.", positioning: { category: "guided coordination platform", target_audience: "College students who want to build", core_problem: "Students waste the first hours searching for reliable teammates.", value_proposition: "Find the right teammates before the clock starts, then ship with momentum.", differentiator: "It turns a vague need into a relevant, human-feeling match.", positioning_statement: "For college builders who need a crew, Campus Relay makes the right teammate easy to find before the clock starts.", competitive_angle: "Clarity and fit over noisy directories." }, personality: { traits: ["Open", "Resourceful", "Specific", "Momentum-driven"], principles: ["Make the next step obvious", "Invite before you impress", "Reward useful momentum"], traits_to_avoid: ["Corporate", "Generic", "Overly formal"] }, selected: 1 };

const steps: Array<[Stage, string]> = [["create", "Idea"], ["discovery", "Discovery"], ["positioning", "Positioning"], ["battle", "Brand Battle"], ["critic", "Critic"], ["kit", "Brand Kit"]];

function localDirections(state: State): Direction[] { const subject = state.name; return [{ direction_name: "Make it real", strategic_territory: "Builder / technical", concept: `A practical engine for making ${subject} useful fast.`, emotional_territory: "Capability and momentum", naming_style: "Compact verbs and construction language", sample_names: ["Forge", "Stackmate", "Buildloop"], tagline_direction: "Find the right move. Make it real.", personality: ["Precise", "Energetic", "Capable"], strengths: ["Feels actionable", "Signals progress"], weaknesses: ["Can sound like a tool"] }, { direction_name: "Find your people", strategic_territory: "Community / crew", concept: "A welcoming signal for the people who make a good idea click.", emotional_territory: "Belonging and recognition", naming_style: "Warm, human, easy-to-say names", sample_names: ["Kinship", "Orbit", "Roommate"], tagline_direction: "Good ideas need the right room.", personality: ["Open", "Warm", "Encouraging"], strengths: ["Lowers first-step anxiety", "Strong emotional hook"], weaknesses: ["Needs proof of speed"] }, { direction_name: "Enter the arena", strategic_territory: "Competitive / arena", concept: "A rallying point for ambitious people working against the clock.", emotional_territory: "Urgency and earned pride", naming_style: "Short, kinetic, game-adjacent names", sample_names: ["Rally", "Bracket", "Draftday"], tagline_direction: "Build your winning team.", personality: ["Bold", "Fast", "Ambitious"], strengths: ["Memorable energy", "Creates urgency"], weaknesses: ["May intimidate beginners"] }]; }

export default function Home() {
  const [stage, setStage] = useState<Stage>("create");
  const [state, setState] = useState<State>(demo);
  const [name, setName] = useState(""); const [idea, setIdea] = useState(""); const [answers, setAnswers] = useState({ audience: "", problem: "", alternatives: "" });
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [demoMode, setDemoMode] = useState(true); const [hydrated, setHydrated] = useState(false);
  const selected = state.directions?.[state.selected ?? 1];
  useEffect(() => {
    try {
      const snapshot = JSON.parse(window.localStorage.getItem("brandforge-mvp") || "null");
      startTransition(() => {
        if (snapshot?.stage) setStage(snapshot.stage);
        if (snapshot?.state) setState(snapshot.state);
        if (snapshot?.name) setName(snapshot.name);
        if (snapshot?.idea) setIdea(snapshot.idea);
        if (snapshot?.answers) setAnswers(snapshot.answers);
        if (typeof snapshot?.demoMode === "boolean") setDemoMode(snapshot.demoMode);
        setHydrated(true);
      });
    } catch {
      window.localStorage.removeItem("brandforge-mvp");
      startTransition(() => setHydrated(true));
    }
  }, []);
  useEffect(() => {
    if (hydrated) window.localStorage.setItem("brandforge-mvp", JSON.stringify({ stage, state, name, idea, answers, demoMode }));
  }, [answers, demoMode, hydrated, idea, name, stage, state]);
  const run = async (next: Stage, action: () => Promise<void>) => { setBusy(true); setError(""); try { await action(); setStage(next); } catch (e) { setError(e instanceof Error ? e.message : "Something went wrong. Your current state is preserved."); } finally { setBusy(false); } };
  const create = () => run("discovery", async () => { if (!name.trim() || idea.trim().length < 10) throw new Error("Add a project name and an idea of at least 10 characters."); if (!demoMode) { const response = await fetch("/api/projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, idea }) }); if (!response.ok) throw new Error("Could not create the project."); } setState({ id: crypto.randomUUID(), name: name.trim(), idea: idea.trim() }); });
  const discover = () => run("positioning", async () => { const audience = (answers.audience || "early adopters").trim().replace(/[.!?]+$/, ""); const problem = (answers.problem || state.idea).trim().replace(/[.!?]+$/, ""); const next = { ...state, audience, problem, alternatives: answers.alternatives, positioning: { category: "guided coordination platform", target_audience: audience, core_problem: problem, value_proposition: `Help ${audience.toLowerCase()} move from uncertainty to a confident first step.`, differentiator: "It turns a vague need into a relevant, human-feeling next action.", positioning_statement: `For ${audience.toLowerCase()} who need ${problem.toLowerCase()}, ${state.name} makes the right next move feel obvious.`, competitive_angle: "Clarity and fit over noisy, generic alternatives." } }; setState(next); });
  const strategy = () => run("battle", async () => { const next = { ...state, positioning: { category: "guided coordination platform", target_audience: state.audience || "early adopters", core_problem: state.problem || state.idea, value_proposition: `Help ${state.audience || "people who need this"} move from uncertainty to a confident first step.`, differentiator: "It turns a vague need into a relevant, human-feeling next action.", positioning_statement: `For ${state.audience || "early adopters"} who need ${state.problem || "a clearer path"}, ${state.name} makes the right next move feel obvious.`, competitive_angle: "Clarity and fit over noisy, generic alternatives." }, personality: demo.personality, directions: localDirections(state) }; setState(next); });
  const battle = () => run("critic", async () => { const evaluations = (state.directions || []).map((_, i) => ({ decision: i === 1 ? "KEEP" : "REVISE", scores: { audience_fit: i === 1 ? 9 : 7, problem_alignment: 8, distinctiveness: i === 1 ? 8 : 6, memorability: i === 2 ? 8 : 7, clarity: 8, personality_alignment: 8, genericity_risk: i === 1 ? 2 : 6, consistency: 8 }, issues: i === 1 ? [] : ["The territory needs a more ownable verbal hook."], evidence: ["This score uses the submitted audience, problem, and positioning."], recommendations: i === 1 ? ["Protect the welcoming language in future copy."] : ["Replace familiar category language with a sharper cue."] })); setState({ ...state, evaluations }); });
  const select = (index: number) => run("kit", async () => { const direction = state.directions?.[index]; if (!direction) throw new Error("Choose a valid direction."); setState({ ...state, selected: index, final: { name: direction.sample_names[0], tagline: direction.tagline_direction, pitch: state.positioning?.value_proposition || "A clearer way to make the next move." } }); });
  const loadDemo = () => { setState({ ...demo, directions: localDirections(demo) }); setAnswers({ audience: demo.audience || "", problem: demo.problem || "", alternatives: demo.alternatives || "" }); setStage("discovery"); };
  return <main className="mvp-shell"><aside className="mvp-sidebar"><div className="brand-mark"><span>BF</span><div><strong>BRANDFORGE</strong><small>AI BRAND STUDIO</small></div></div><div className="demo-pill"><i /> {demoMode ? "DEMO MODE" : "BUILD FROM SCRATCH"}</div><button className="mode-toggle" onClick={() => setDemoMode(!demoMode)}>{demoMode ? "Switch to build from scratch" : "Use demo mode"}</button><nav>{steps.map(([key, label], i) => <button key={key} onClick={() => key === "kit" && state.final ? setStage(key) : undefined} className={stage === key ? "active" : ""}><span>0{i + 1}</span>{label}{stage === key && <b>›</b>}</button>)}</nav><button className="reset-link" onClick={() => { setStage("create"); setState(demo); }}>+ New brand</button></aside><section className="mvp-content"><header className="mvp-topbar"><span>WORKSPACE / {state.name.toUpperCase()}</span><span className="live-chip">● {demoMode ? "DEMO DATA" : "LOCAL WORKFLOW"}</span></header>{error && <div className="error-banner">{error}</div>}{busy && <div className="processing">Processing structured brand state...</div>}{stage === "create" && <Create name={name} setName={setName} idea={idea} setIdea={setIdea} onCreate={create} onDemo={loadDemo} />}{stage === "discovery" && <Discovery answers={answers} setAnswers={setAnswers} onNext={discover} />}{stage === "positioning" && <Positioning state={state} onNext={strategy} />}{stage === "battle" && <Battle state={state} onNext={battle} />}{stage === "critic" && <Critic state={state} onSelect={select} />}{stage === "kit" && <Kit state={state} selected={selected} />}</section></main>;
}

function Create({ name, setName, idea, setIdea, onCreate, onDemo }: { name: string; setName: (x: string) => void; idea: string; setIdea: (x: string) => void; onCreate: () => void; onDemo: () => void }) { return <div className="mvp-center"><p className="eyebrow">START WITH A SIGNAL</p><h1>Turn a rough idea into<br /><em>a brand people remember.</em></h1><p className="lede">BrandForge moves in stages: understand, position, challenge, choose. You stay in the loop at every decision.</p><div className="create-form"><label>PROJECT NAME<input value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Campus Relay" /></label><label>ROUGH IDEA<textarea value={idea} onChange={e => setIdea(e.target.value)} placeholder="What are you building, for whom, and why does it matter?" /></label><button className="primary-button" onClick={onCreate}>Start discovery <span>→</span></button></div><button className="demo-link" onClick={onDemo}>Open Campus Relay demo ↗</button></div>; }
function Discovery({ answers, setAnswers, onNext }: { answers: { audience: string; problem: string; alternatives: string }; setAnswers: (x: { audience: string; problem: string; alternatives: string }) => void; onNext: () => void }) { return <div className="mvp-page"><p className="eyebrow">STAGE 01 / ADAPTIVE DISCOVERY</p><h1>Let&apos;s find the real<br /><em>problem underneath.</em></h1><p className="lede">These questions are chosen because their answers change the brand strategy. Nothing decorative gets in the way.</p><div className="question-grid">{[["audience", "Who is the primary user you want to win first?", "Audience language determines the brand center of gravity."], ["problem", "What frustrating problem are they experiencing today?", "A specific tension produces a sharper position."], ["alternatives", "What do they use or do instead right now?", "The alternative reveals where your difference can matter."]].map(([key, q, why]) => <label key={key}><span>QUESTION {key === "audience" ? "01" : key === "problem" ? "02" : "03"}</span><strong>{q}</strong><small>{why}</small><textarea value={answers[key as keyof typeof answers]} onChange={e => setAnswers({ ...answers, [key]: e.target.value })} /></label>)}</div><button className="primary-button" onClick={onNext}>Build my positioning <span>→</span></button></div>; }
function Positioning({ state, onNext }: { state: State; onNext: () => void }) { const p = state.positioning; return <div className="mvp-page"><p className="eyebrow">STAGE 02 / POSITIONING</p><h1>Here&apos;s the signal<br /><em>we found.</em></h1><div className="strategy-card"><div><small>CATEGORY</small><strong>{p?.category}</strong></div><div><small>CORE PROBLEM</small><p>{p?.core_problem}</p></div><div><small>VALUE PROPOSITION</small><p>{p?.value_proposition}</p></div><div><small>DIFFERENTIATOR</small><p>{p?.differentiator}</p></div><div className="full"><small>POSITIONING STATEMENT</small><strong>{p?.positioning_statement}</strong></div></div><button className="primary-button" onClick={onNext}>Shape the personality <span>→</span></button></div>; }
function Battle({ state, onNext }: { state: State; onNext: () => void }) { return <div className="mvp-page wide"><p className="eyebrow">STAGE 04 / BRAND BATTLE</p><h1>Three ways to<br /><em>own the idea.</em></h1><p className="lede">These directions are strategic territories, not random name lists. Compare the emotional bet each one makes.</p><div className="battle-grid">{state.directions?.map((d, i) => <article className={`mvp-direction d${i}`} key={d.direction_name}><small>0{i + 1} / {d.strategic_territory.toUpperCase()}</small><h2>{d.direction_name}</h2><p>{d.concept}</p><div className="names">{d.sample_names.map(n => <span key={n}>{n}</span>)}</div><hr /><small>EMOTIONAL TERRITORY</small><strong>{d.emotional_territory}</strong><small>NAMING STYLE</small><strong>{d.naming_style}</strong><small>STRENGTHS</small><p>{d.strengths.join(" · ")}</p><small>WEAKNESS</small><p className="risk">{d.weaknesses.join(" · ")}</p></article>)}</div><button className="primary-button" onClick={onNext}>Challenge the directions <span>→</span></button></div>; }
function Critic({ state, onSelect }: { state: State; onSelect: (i: number) => void }) { return <div className="mvp-page wide"><p className="eyebrow">STAGE 05 / ANTI-GENERIC CRITIC</p><h1>Keep the strong.<br /><em>Challenge the easy.</em></h1><p className="lede">The critic checks every direction against your audience, problem, and personality. Scores are signals, not scientific measurements.</p><div className="critic-list">{state.directions?.map((d, i) => { const e = state.evaluations?.[i]; return <article key={d.direction_name}><div><small>{d.strategic_territory.toUpperCase()}</small><h2>{d.direction_name}</h2><p>{e?.evidence.join(" ")}</p></div><div className="score-box"><strong>{e?.scores.audience_fit}/10</strong><small>AUDIENCE FIT</small><strong>{e?.scores.distinctiveness}/10</strong><small>DISTINCTIVE</small></div><div className="critic-note"><b>{e?.decision}</b><p>{e?.issues.length ? e.issues.join(" ") : "Strongest fit: clear, welcoming, and connected to the stated problem."}</p><button onClick={() => onSelect(i)}>Select direction →</button></div></article> })}</div></div>; }
function Kit({ state, selected }: { state: State; selected?: Direction }) { return <div className="mvp-page wide"><p className="eyebrow">STAGE 07 / FINAL BRAND KIT</p><h1>{state.final?.name || selected?.sample_names[0]}</h1><p className="lede">A coherent system built from your discovery, strategy, and selected direction.</p><div className="kit-hero"><small>TAGLINE</small><h2>{state.final?.tagline || selected?.tagline_direction}</h2><p>{state.final?.pitch}</p></div><div className="kit-columns"><section><small>STRATEGY</small><h3>{state.positioning?.value_proposition}</h3><p>{state.positioning?.positioning_statement}</p></section><section><small>PERSONALITY</small><div className="tags">{state.personality?.traits.map(t => <span key={t}>{t}</span>)}</div><p>Principles: {state.personality?.principles.join(" · ")}</p></section><section><small>QUALITY CHECK</small><h3>Audience fit 9 / 10</h3><p>Distinctive 8 / 10 · Clarity 8 / 10 · Consistency 8 / 10</p></section></div></div>; }
